apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc-node2
  namespace: test
spec:
  ports:
  - name: 8063-30009
    port: 8063
    nodePort: 30009
  selector:
    app: py-web-test
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-web-test-deploy2
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py-web-test
  template:
    metadata:
      labels:
        app: py-web-test
    spec:
      containers:
      - name: py-web-test
        image: 192.168.132.129:5000/web_test2:latest
        env:
        - name: version
          value: '4.0'
        ports:
        - containerPort: 8063